"""The plug-in contract every vertical (Resume, Marketing, Automotive, Legal...)
must satisfy to run on the shared engine.

The scope document's core design principle is: "Nothing in the core engine is
domain-specific... each vertical plugs into the same orchestration graph by
supplying its own prompts, extraction schemas, validation rules, and tools."
This dataclass is that plug-in point.
"""
from dataclasses import dataclass
from typing import Any, Callable

from pydantic import BaseModel


@dataclass
class VerticalConfig:
    name: str
    output_schema: type[BaseModel]
    required_fields: list[str]

    extraction_prompt: str
    generation_prompt: str
    clarification_prompt: str

    # Optional extra business-rule validation beyond schema validation
    # (e.g. duplicate detection, cross-field consistency checks).
    extra_validators: list[Callable[[BaseModel], list[str]]] | None = None

    # Optional deeper completeness check, run in addition to the flat
    # `required_fields` presence check. `required_fields` can only tell you
    # a top-level key exists (e.g. "work_experience" is a non-empty list) -
    # this hook lets a vertical flag that what's *inside* it is still too
    # thin to generate a good result (e.g. a work entry with no job title),
    # returning extra virtual field names to add to `missing_fields` so the
    # normal clarify/resume loop asks about them too.
    extra_missing_check: Callable[[dict], list[str]] | None = None

    # Optional human-readable hint per field key (including virtual ones from
    # `extra_missing_check`), used as: (a) fallback context for the
    # deterministic clarify-question templating below when a field has no
    # entry in `field_questions`, and (b) a debugging/logging aid.
    field_hints: dict[str, str] | None = None

    # Optional pre-written, per-language question text for known field keys
    # (including virtual ones from `extra_missing_check`), keyed like
    # `{"full_name": {"en": "...", "ar": "..."}}`. The clarify node prefers
    # this over calling a model: since the *set* of fields a vertical can
    # ever ask about is fixed ahead of time (its own schema + completeness
    # checks), phrasing each one is a one-time authoring cost, not something
    # that benefits from being regenerated by an LLM on every request. Only
    # fields missing from this map (or a language missing from an entry,
    # which falls back to "en") fall through to a generic templated
    # question built from `field_hints` - never to an LLM call.
    field_questions: dict[str, dict[str, str]] | None = None

    # Optional per-language display name for fields that conflict-detection
    # can flag (see `_detect_conflicts`/EXTRACTION_PROMPT's `conflicts`
    # convention), e.g. `{"email": {"en": "your email", "ar": "..."}}`.
    # Used to phrase a `conflict::<field>` question deterministically
    # ("I found different information for <label>: ...") without an LLM.
    # Falls back to the raw field key (humanized) if a field has no entry.
    conflict_field_labels: dict[str, dict[str, str]] | None = None

    # Optional LangChain tools (functions decorated with `@tool`, or anything
    # else `Runnable.bind_tools()` accepts) the model can call before final
    # generation - e.g. normalizing a date, computing a derived value,
    # looking something up. Used by the tool-use node only as a fallback
    # when `deterministic_enrichment` (below) isn't set. Left empty (and no
    # `deterministic_enrichment`), the tool-use node is a no-op, so
    # verticals that don't need either pay zero extra cost.
    tools: list[Any] | None = None

    # Optional plain function that enriches `extracted_data` before
    # generation with zero judgment calls to make (e.g. "always normalize
    # every date to YYYY-MM") - i.e. exactly the kind of thing `tools` above
    # would otherwise ask a model to decide whether to do. When set, the
    # tool-use node calls this directly and never touches an LLM; `tools`
    # is only consulted as a fallback for verticals that need genuine
    # model-mediated tool selection instead.
    deterministic_enrichment: Callable[[dict], dict] | None = None

    max_retries: int = 2

    # Once no required/completeness fields and no conflicts remain, ask the
    # user a final "generate now, or is there more?" confirmation before
    # spending a generation call - gives them one last deliberate chance to
    # add anything the automatic gap-detection didn't think to ask about.
    # Runs through the same generic clarify/merge/gap-check loop as any other
    # missing field (see `_CONFIRM_FIELD` in app/graph/nodes.py), so it costs
    # zero extra LLM calls: the question itself is fixed/deterministic, and
    # it only repeats if the user actually adds more info instead of
    # confirming. Set to False to skip it and generate immediately.
    confirm_before_generate: bool = True
